Much more progress with postgresql extension.

diff --git a/postgresql/shell/functions b/postgresql/shell/functions
--- a/postgresql/shell/functions
+++ b/postgresql/shell/functions
@@ -1,25 +1,7 @@
 #!/bin/sh
 
-typeset -ga configure_flags >/dev/null 2>&1 # Don't care if declared already.
-
-postgresql_initialize()
+postgresql_defaults()
 {
-  trace_filter postgresql || set -o xtrace
-
-  PATH="${sm_path}/bin:${sm_path}/pkg/active/bin:${sm_path}/pkg/active/sbin:$PATH"
-  export PATH
-
-  true \
-    ${service_port:=5432} \
-    ${service_bind_interface:="127.0.0.1"}
-
-  service initialize
-
-  config read file defaults from postgresql version key version prefix package
-
-  service_binary="${service_bin_path}/pg_ctl"
-  service_cli_binary="${service_bin_path}/psql"
-
   if user is root
   then
     if os is darwin
@@ -31,22 +13,55 @@ postgresql_initialize()
   else
     service_user="$USER"
   fi
-  package_user="${service_user}"
 
-  local _action
+  if [[ ${service_user} == "postgresql" ]]
+  then service_user="postgres" ; fi
 
   service_data_path="${service_db_path}/${package_version}/data"
+
+  json get from ${extension_path}/config/defaults.json \
+    into "postgresql_defaults" \
+    string "postgresql/bind" default 0.0.0.0 as "bind" \
+    string "postgresql/port" default 5432 as "port" \
+    string "postgresql/syslog/facility" default "local0" as "syslog_facility"\
+    string "postgresql/max/clients" default 128 as "max_clients" \
+    string "postgresql/max/memory" default "128mb" as "max_memory" \
+    string "postgresql/max/slow" default 1024 as "max_sloq" \
+    string "postgresql/log/slow" default 10000 as "log_slow" \
+    string "postgresql/data/path" default "${service_data_path}" as "data_path" \
+    string "postgresql/service/bin_path" as "service_bin_path" default "${sm_path}/pkg/active/bin" \
+    string "postgresql/service/pid_file" as "service_pid_file" default "/var/run/postgresql/postgresql.pid" \
+    string "postgresql/service/config_file" as "service_config_file" default "/etc/postgresql/postgresql.conf" \
+    string "postgresql/service/log_file" as "service_log_file" default "/var/log/postgresql/postgresql.log" \
+    string "postgresql/service/user" as "service_user" default "${service_user}" \
+    string "postgresql/service/data_path" as "service_data_path" default "${service_data_path}" \
+    string "postgresql/start/timeout" as "start_timeout" default "300" \
+    string "postgresql/replication/master" as "master" default "localhost"
+
+  PGDATA="${service_data_path}"
+}
+
+postgresql_initialize()
+{
+  trace_filter postgresql || set -o xtrace
+  local _action
+
+  postgresql_defaults
+
+  service initialize
+
+  config read file defaults from postgresql version key version prefix package
+
+  service_binary="${service_bin_path}/pg_ctl"
+  service_cli_binary="${service_bin_path}/psql"
+  package_user="${service_user}"
+
   if array is empty service_flags
   then
     _action="${action//\(*}"
     service_flags+=(${_action//*_} -D "$service_data_path" -s )
     service_stop_flags+=( -m fast -w )
   fi
-
-  typeset -gx PGDATA
-  PGDATA="${service_data_path}"
-
-  service_pid_file="/var/run/postgresql/postgresql.pid"
 }
 
 postgresql_prefetch()
@@ -55,21 +70,20 @@ postgresql_prefetch()
     base_url "http://ftp9.us.postgresql.org/pub/mirrors/postgresql/source/v${package_version}"
 }
 
-postgresql_database_setup()
+postgresql_database_initialize()
 {
-  local _file _command _initdb_flags file _entries
+  local _file _command _initdb_flags file _entries _dir
 
   paths create "${log_path}" # "${service_db_path}"
   path chown "$service_user:$service_user" recursively "${log_path}"
 
-  if [[ ${service_user} == "postgresql" ]]
-  then service_user="postgres" ; fi
-
-  if ! path exists "${service_data_path}"
+  if path exists "${service_data_path}/base"
   then
+    log warn "The database in '${service_data_path}' has already been initialized."
+  else
     log "Initializing postgresql data directory in $service_data_path"
 
-    _initdb_flags=(
+    _initdb_flags+=(
     --pgdata="'${service_data_path}'"
     --encoding=utf8
     --locale=C
@@ -83,39 +97,21 @@ postgresql_database_setup()
     if user is root
     then
       if ! su - "${service_user}" -c "${_command}"
-      then
-        __sm.log.warn "initdb failed, command:\n${_command}"
-      fi
+      then __sm.log.warn "initdb failed, command:\n${_command}" ; fi
     else
       if ! "${_command}"
-      then
-        __sm.log.warn "initdb failed, command:\n${_command}"
-      fi
+      then __sm.log.warn "initdb failed, command:\n${_command}" ; fi
     fi
   fi
 
-  for file in postgresql pg_hba pg_ident recovery
+  for _dir in archives wal
   do
-    if file is missing "${service_data_path}/${file}.conf"
-    then
-      if file is missing "${service_data_path}/${file}.conf.sample"
-      then
-        continue
-      fi
-      log "Installing ${file}.conf to ${service_data_path}/"
-      files copy force \
-        from "$service_data_path/${file}.conf.sample" \
-        to "$service_data_path/${file}.conf"
-    fi
+    if ! path exists "${service_db_path}/${_dir}"
+    then paths create "${service_db_path}/${_dir}" ; fi
   done
 
   path chown "$service_user:$service_user" recursively "${service_data_path}"
   path chmod 0700 recursively "${service_data_path}"
-}
-
-postgresql_service_setup()
-{
-  postgresql_database_setup
 }
 
 postgresql_preconfigure()
@@ -132,16 +128,23 @@ postgresql_preconfigure()
   fi
 }
 
+postgresql_uninstall()
+{
+  local _file
 
-postgresql_uninstall() {
-  paths remove \
-    "${prefix_path}/${package_name}" \
+  paths remove "${prefix_path}/${package_name}" \
     "${prefix_path}/${package_name}-${package_version}"
 
-  remove_files \
-    /etc/profile.d/postgresql.sh \
-    /etc/ld.so.conf.d/postgresql.conf \
-    "${init_scripts_path}/postgresql"
+  for _file in "/etc/profile.d/postgresql.sh" \
+    "${init_scripts_path}/postgresql" \
+    "/etc/monit.d/postgresql" \
+    "/lib/systemd/system/postgresql.service"
+  do
+    if _file exists "$_file"
+    then
+      file remove "$_file"
+    fi
+  done
 
   user delete "${package_user}"
 
