Moved the initialize for pgha around

diff --git a/pgha/bin/run b/pgha/bin/run
--- a/pgha/bin/run
+++ b/pgha/bin/run
@@ -25,6 +25,12 @@
 # Keep track of where we go next.
 #
 
+if [[ -z ${masterIP} ]]
+then
+    echo "ERROR: pgha can not run, a master IP has not been set in ${masterFile}"
+    exit 1
+fi
+
 (( ${DEBUG:=0} == 0 )) || set -x
 
 exec &> ${pghaLog}
